# Generated by Django 5.1.6 on 2025-02-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='proPic/original')),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('is_user', models.BooleanField(default=False)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
