# Generated by Django 5.2 on 2025-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_myevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myevent',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='event',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
