# Generated by Django 5.2 on 2025-04-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reading_level',
        ),
    ]
